#!/bin/bash
# Create Plugin

echo deleting old files
rm SelectiveCompiling.cbplugin

echo copy files
cp -f TestScriptPlugin/install.xml resources/install.xml
cp -f TestScriptPlugin/manifest.xml resources/manifest.xml

echo Compressing Resources
zip -jqu9 SelectiveCompiling.zip resources/*
zip -jqu9 tmp_SelectiveCompiling.zip TestScriptPlugin/* 
zip -jqu9 tmp_SelectiveCompiling.zip SelectiveCompiling.zip

echo rename files
mv tmp_SelectiveCompiling.zip SelectiveCompiling.cbplugin

echo deleting temp files
rm SelectiveCompiling.zip
rm tmp_SelectiveCompiling.zip

