
/*
 * This file is part of the Code::Blocks IDE and licensed under the GNU General Public License, version 3
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * $Revision$
 * $Id$
 * $HeadURL$
 */

// user-dialog-test
// Script plugins must extend cbScriptPlugin

local dialog_res = @"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVR
GLTgiIHN0YW5kYWxvbmU9InllcyIgPz4KPHJlc291cmNlIHhtbG5zPSJodHRwOi8
vd3d3Lnd4d2luZG93cy5vcmcvd3h4cmMiPgoJPG9iamVjdCBjbGFzcz0id3hEaWF
sb2ciIG5hbWU9Imluc3RhbGxfZGlhbG9nIj4KCQk8dGl0bGU+SW5zdGFsbGluZyB
jYlNlbGVjdGl2ZUNvbXBpbGluZzwvdGl0bGU+CgkJPGNlbnRlcmVkPjE8L2NlbnR
lcmVkPgoJCTxvYmplY3QgY2xhc3M9Ind4RmxleEdyaWRTaXplciI+CgkJCTxjb2x
zPjE8L2NvbHM+CgkJCTxvYmplY3QgY2xhc3M9InNpemVyaXRlbSI+CgkJCQk8b2J
qZWN0IGNsYXNzPSJ3eFN0YXRpY1RleHQiIG5hbWU9IklEX1NUQVRJQ1RFWFQxIj4
KCQkJCQk8bGFiZWw+RG8geW91IHdhbnQgdG8gaW5zdGFsbCBjYlNlbGVjdGl2ZUN
vbXBpbGluZyBwbHVnaW4/PC9sYWJlbD4KCQkJCTwvb2JqZWN0PgoJCQkJPGZsYWc
+d3hBTEx8d3hBTElHTl9DRU5URVJfSE9SSVpPTlRBTHx3eEFMSUdOX0NFTlRFUl9
WRVJUSUNBTDwvZmxhZz4KCQkJCTxib3JkZXI+NTwvYm9yZGVyPgoJCQkJPG9wdGl
vbj4xPC9vcHRpb24+CgkJCTwvb2JqZWN0PgoJCQk8b2JqZWN0IGNsYXNzPSJzaXp
lcml0ZW0iPgoJCQkJPG9iamVjdCBjbGFzcz0id3hIeXBlcmxpbmtDdHJsIiBuYW1
lPSJtX2xpbmsiPgoJCQkJCTxsYWJlbD5odHRwczovL2dpdGh1Yi5jb20vYmx1ZWh
henphcmQvY2RTZWxlY3RpdmVDb21waWxpbmc8L2xhYmVsPgoJCQkJPC9vYmplY3Q
+CgkJCQk8ZmxhZz53eEFMTHx3eEFMSUdOX0NFTlRFUl9IT1JJWk9OVEFMfHd4QUx
JR05fQ0VOVEVSX1ZFUlRJQ0FMPC9mbGFnPgoJCQkJPGJvcmRlcj41PC9ib3JkZXI
+CgkJCQk8b3B0aW9uPjE8L29wdGlvbj4KCQkJPC9vYmplY3Q+CgkJCTxvYmplY3Q
gY2xhc3M9InNpemVyaXRlbSI+CgkJCQk8b2JqZWN0IGNsYXNzPSJ3eEJveFNpemV
yIj4KCQkJCQk8b2JqZWN0IGNsYXNzPSJzaXplcml0ZW0iPgoJCQkJCQk8b2JqZWN
0IGNsYXNzPSJ3eEJ1dHRvbiIgbmFtZT0ibV9iX3llcyI+CgkJCQkJCQk8bGFiZWw
+WUVTPC9sYWJlbD4KCQkJCQkJPC9vYmplY3Q+CgkJCQkJCTxmbGFnPnd4QUxMfHd
4QUxJR05fQ0VOVEVSX0hPUklaT05UQUx8d3hBTElHTl9DRU5URVJfVkVSVElDQUw
8L2ZsYWc+CgkJCQkJCTxib3JkZXI+NTwvYm9yZGVyPgoJCQkJCQk8b3B0aW9uPjE
8L29wdGlvbj4KCQkJCQk8L29iamVjdD4KCQkJCQk8b2JqZWN0IGNsYXNzPSJzaXp
lcml0ZW0iPgoJCQkJCQk8b2JqZWN0IGNsYXNzPSJ3eEJ1dHRvbiIgbmFtZT0ibV9
iX25vIj4KCQkJCQkJCTxsYWJlbD5OTzwvbGFiZWw+CgkJCQkJCTwvb2JqZWN0Pgo
JCQkJCQk8ZmxhZz53eEFMTHx3eEFMSUdOX0NFTlRFUl9IT1JJWk9OVEFMfHd4QUx
JR05fQ0VOVEVSX1ZFUlRJQ0FMPC9mbGFnPgoJCQkJCQk8Ym9yZGVyPjU8L2JvcmR
lcj4KCQkJCQkJPG9wdGlvbj4xPC9vcHRpb24+CgkJCQkJPC9vYmplY3Q+CgkJCQk
8L29iamVjdD4KCQkJCTxmbGFnPnd4QUxMfHd4QUxJR05fQ0VOVEVSX0hPUklaT05
UQUx8d3hBTElHTl9DRU5URVJfVkVSVElDQUw8L2ZsYWc+CgkJCQk8Ym9yZGVyPjU
8L2JvcmRlcj4KCQkJCTxvcHRpb24+MTwvb3B0aW9uPgoJCQk8L29iamVjdD4KCQk
8L29iamVjdD4KCTwvb2JqZWN0Pgo8L3Jlc291cmNlPg=="

/*local dialog_res = @"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVR
GLTgiIHN0YW5kYWxvbmU9InllcyIgPz4NCjxyZXNvdXJjZSB4bWxucz0iaHR0cDo
vL3d3dy53eHdpbmRvd3Mub3JnL3d4eHJjIiB2ZXJzaW9uPSIyLjUuMy4wIj4NCgk
8b2JqZWN0IGNsYXNzPSJ3eERpYWxvZyIgbmFtZT0iaW5zdGFsbF9kaWFsb2ciPg0
KCQk8dGl0bGU+SW5zdGFsbGluZyBjYlNlbGVjdGl2ZUNvbXBpbGluZzwvdGl0bGU
+DQoJCTxjZW50ZXJlZD4xPC9jZW50ZXJlZD4NCgkJPG9iamVjdCBjbGFzcz0id3h
GbGV4R3JpZFNpemVyIj4NCgkJCTxjb2xzPjE8L2NvbHM+DQoJCQk8b2JqZWN0IGN
sYXNzPSJzaXplcml0ZW0iPg0KCQkJCTxvYmplY3QgY2xhc3M9Ind4U3RhdGljVGV
4dCIgbmFtZT0iSURfU1RBVElDVEVYVDEiPg0KCQkJCQk8bGFiZWw+RG8geW91IHd
hbnQgdG8gaW5zdGFsbCBjYlNlbGVjdGl2ZUNvbXBpbGluZyBwbHVnaW4/PC9sYWJ
lbD4NCgkJCQk8L29iamVjdD4NCgkJCQk8ZmxhZz53eEFMTHx3eEFMSUdOX0NFTlR
FUl9IT1JJWk9OVEFMfHd4QUxJR05fQ0VOVEVSX1ZFUlRJQ0FMPC9mbGFnPg0KCQk
JCTxib3JkZXI+NTwvYm9yZGVyPg0KCQkJCTxvcHRpb24+MTwvb3B0aW9uPg0KCQk
JPC9vYmplY3Q+DQoJCQk8b2JqZWN0IGNsYXNzPSJzaXplcml0ZW0iPg0KCQkJCTx
vYmplY3QgY2xhc3M9Ind4SHlwZXJsaW5rQ3RybCIgbmFtZT0ibV9saW5rIj4NCgk
JCQkJPGxhYmVsPmh0dHBzOi8vZ2l0aHViLmNvbS9ibHVlaGF6emFyZC9jZFNlbGV
jdGl2ZUNvbXBpbGluZzwvbGFiZWw+DQoJCQkJPC9vYmplY3Q+DQoJCQkJPGZsYWc
+d3hBTEx8d3hBTElHTl9DRU5URVJfSE9SSVpPTlRBTHx3eEFMSUdOX0NFTlRFUl9
WRVJUSUNBTDwvZmxhZz4NCgkJCQk8Ym9yZGVyPjU8L2JvcmRlcj4NCgkJCQk8b3B
0aW9uPjE8L29wdGlvbj4NCgkJCTwvb2JqZWN0Pg0KCQkJPG9iamVjdCBjbGFzcz0
ic2l6ZXJpdGVtIj4NCgkJCQk8b2JqZWN0IGNsYXNzPSJ3eEJveFNpemVyIj4NCgk
JCQkJPG9iamVjdCBjbGFzcz0ic2l6ZXJpdGVtIj4NCgkJCQkJCTxvYmplY3QgY2x
hc3M9Ind4QnV0dG9uIiBuYW1lPSJtX2JfeWVzIj4NCgkJCQkJCQk8bGFiZWw+WUV
TPC9sYWJlbD4NCgkJCQkJCTwvb2JqZWN0Pg0KCQkJCQkJPGZsYWc+d3hBTEx8d3h
BTElHTl9DRU5URVJfSE9SSVpPTlRBTHx3eEFMSUdOX0NFTlRFUl9WRVJUSUNBTDw
vZmxhZz4NCgkJCQkJCTxib3JkZXI+NTwvYm9yZGVyPg0KCQkJCQkJPG9wdGlvbj4
xPC9vcHRpb24+DQoJCQkJCTwvb2JqZWN0Pg0KCQkJCQk8b2JqZWN0IGNsYXNzPSJ
zaXplcml0ZW0iPg0KCQkJCQkJPG9iamVjdCBjbGFzcz0id3hCdXR0b24iIG5hbWU
9Im1fYl9ubyI+DQoJCQkJCQkJPGxhYmVsPk5PPC9sYWJlbD4NCgkJCQkJCTwvb2J
qZWN0Pg0KCQkJCQkJPGZsYWc+d3hBTEx8d3hBTElHTl9DRU5URVJfSE9SSVpPTlR
BTHx3eEFMSUdOX0NFTlRFUl9WRVJUSUNBTDwvZmxhZz4NCgkJCQkJCTxib3JkZXI
+NTwvYm9yZGVyPg0KCQkJCQkJPG9wdGlvbj4xPC9vcHRpb24+DQoJCQkJCTwvb2J
qZWN0Pg0KCQkJCTwvb2JqZWN0Pg0KCQkJCTxmbGFnPnd4QUxMfHd4QUxJR05fQ0V
OVEVSX0hPUklaT05UQUx8d3hBTElHTl9DRU5URVJfVkVSVElDQUw8L2ZsYWc+DQo
JCQkJPGJvcmRlcj41PC9ib3JkZXI+DQoJCQkJPG9wdGlvbj4xPC9vcHRpb24+DQo
JCQk8L29iamVjdD4NCgkJPC9vYmplY3Q+DQoJPC9vYmplY3Q+DQo8L3Jlc291cmN
lPg=="*/


class tmp_install_plugin extends cbScriptPlugin
{

    // mandatory to setup the plugin's info
    constructor()
    {
        info = ::PluginInfo();

        info.name = ::_T("tmp_install_plugin");
        info.title = ::_T("tmp_install_plugin");
        info.version = ::_T("0.1a");
        info.license = ::_T("GPL");
    }

    function RemoveNewLine(str)
    {
        local tmp = ::wxString(str);
        tmp.Replace("\n","",true);
        return tmp;
    }


    function DisplayError(message)
	{
		::error(message);
		::ShowMessage(message);
	}

    function GetPluginInfo()
    {
        return info;
    }

    function OnYes(evt)
    {
        main_dialog.EndModal(0);
    }

    function OnNo(evt)
    {
        main_dialog.EndModal(-2);
    }

    function OnLink(evt)
    {
		::wxLaunchDefaultBrowser("https://github.com/bluehazzard/cbSelectiveCompiling",0);
        //::Message("Show page","page",wxOK);
    }

    function ShowDialog()
    {

		if(loaded == false)
		{
			main_dialog = ::CreateWxDialog(this);

			// Load the resource from string
            local tmp_string = RemoveNewLine(dialog_res);
            local tmp_string2 = ::wxBase64Decode(tmp_string);
            ::print(tmp_string2);
			if(::LoadResourceFromString(this,tmp_string2) == false)
			{
				DisplayError("Could not load resource from string");
				return -1;
			}

			local ret = main_dialog.LoadFromXRCPool("install_dialog");
			if(ret != RESOURCE_LOADED_SUCCESFULLY)
			{
				DisplayError("Could not load \"selective_compiling_main_diag\" from Resource pool");
				return -1;
			}

			main_dialog.RegisterEventHandler(wxEVT_BUTTON,::XRCID("m_b_yes"),this,"OnYes");
			main_dialog.RegisterEventHandler(wxEVT_BUTTON,::XRCID("m_b_no"),this,"OnNo");
			main_dialog.RegisterEventHandler(wxEVT_COMMAND_HYPERLINK,::XRCID("m_link"),this,"OnLink");

			loaded = true;

		}



		return main_dialog.ShowModal();

    };

    main_dialog = 0;
	info = 0;
	loaded = false;

}

function pre_install(status)
{
    local plugin = tmp_install_plugin();
    local ret = 0;
    RegisterPlugin(plugin);
    try
    {
        ret = plugin.ShowDialog();
    }
    catch(error_msg)
    {
        Message("Got an error : " + error_msg ,"Install cbSelectiveCompiling",wxOK);
    }
    UnRegisterPlugin("tmp_install_plugin");
    return ret;
}

function post_install(status)
{
        return 0;
}

// this call actually registers the script plugin with Code::Blocks


// if you want to call this plugin's Execute() function, use this in a script:
// ExecutePlugin(_T("Scripting_TestPlugin"));
